import shutil
import subprocess
import json
import os
import logging
from typing import Dict, Any, List

class ReconEngine:
    """
    Advanced Reconnaissance Engine 2.0
    Integrates theHarvester, Shodan, and Google Dorks.
    """
    
    def __init__(self, target: str, options: Dict[str, Any] = None):
        self.target = target
        self.options = options or {}
        self.results = {}
        self.logger = logging.getLogger("ReconEngine")
        
    def _is_tool_available(self, name: str) -> bool:
        return shutil.which(name) is not None

    def run_theharvester(self) -> Dict[str, Any]:
        """
        Runs theHarvester to gather emails, subdomains, hosts, employee names, open ports and banners.
        """
        if not self._is_tool_available("theHarvester"):
             # Fallback: check if it's installed as a python module or script
             # Sometimes it's run as `python3 -m theHarvester`
             pass

        print(f"[*] Starting theHarvester on {self.target}...")
        
        output_file = f"theharvester_{self.target}.json"
        # Command: theHarvester -d target -b all -f filename
        cmd = ["theHarvester", "-d", self.target, "-b", "all", "-f", output_file]
        
        try:
            # We use a reasonably high timeout because theHarvester checks many sources
            subprocess.run(cmd, capture_output=True, text=True, timeout=300)
            
            # The tool might append .json to the filename automatically
            real_filename = output_file
            if not os.path.exists(real_filename) and os.path.exists(real_filename + ".json"):
                real_filename += ".json"
            elif not os.path.exists(real_filename) and os.path.exists(output_file + ".xml"):
                 # older versions might default to xml
                 pass

            data = {}
            if os.path.exists(real_filename):
                try:
                    with open(real_filename, 'r') as f:
                        data = json.load(f)
                    # Clean up
                    os.remove(real_filename)
                    # Also remove xml/html if generated
                    if os.path.exists(output_file + ".xml"): os.remove(output_file + ".xml")
                except Exception as e:
                    return {"error": f"Failed to parse JSON: {e}"}
            else:
                 return {"error": "No output file generated by theHarvester"}

            return {
                "tool": "theHarvester",
                "hosts": data.get("hosts", []),
                "emails": data.get("emails", []),
                "ips": data.get("ips", [])
            }

        except FileNotFoundError:
            return {"error": "theHarvester binary not found in PATH."}
        except subprocess.TimeoutExpired:
            return {"error": "theHarvester timed out."}
        except Exception as e:
            return {"error": f"Execution error: {str(e)}"}

    def run_shodan_api(self, api_key: str = None) -> Dict[str, Any]:
        """
        Queries Shodan API for host information.
        """
        if not api_key:
            api_key = os.environ.get("SHODAN_API_KEY") or self.options.get("shodan_api_key")
        
        if not api_key:
            return {"error": "No Shodan API Key provided."}

        try:
            import shodan
            api = shodan.Shodan(api_key)
            # Lookup the host (resolving target to IP first usually required, but shodan search accepts hostname too mostly)
            # Ideally verify if target is IP or Domain
            info = api.search(self.target)
            return {
                "tool": "Shodan",
                "total": info.get('total'),
                "matches": info.get('matches', [])[:5] # Limit to top 5
            }
        except ImportError:
            return {"error": "shodan python module not installed (pip install shodan)"}
        except Exception as e:
            return {"error": str(e)}

    def run_google_dorks(self) -> Dict[str, Any]:
        """
        Automated Google Dorking using googlesearch-python.
        """
        dorks = [
            f"site:{self.target} ext:pdf",
            f"site:{self.target} ext:xml",
            f"site:{self.target} ext:sql",
            f"site:{self.target} \"password\"",
            f"site:{self.target} inurl:admin"
        ]
        
        results = {}
        
        try:
            from googlesearch import search
            for dork in dorks:
                # 5 secs pause to avoid rate limit if possible, or just rely on lib
                links = []
                for j in search(dork, num=5, stop=5, pause=2):
                    links.append(j)
                if links:
                    results[dork] = links
        except ImportError:
            return {"error": "googlesearch-python not installed"}
        except Exception as e:
            return {"error": f"Dorking failed: {str(e)}"}

        return {
            "tool": "GoogleDorks",
            "findings": results
        }

    def run_all(self):
        return {
            "theharvester": self.run_theharvester(),
            "google_dorks": self.run_google_dorks(),
            # Shodan only if key is present
            "shodan": self.run_shodan_api()
        }
